### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by urbainvaes** [PdIPS/CBX.jl#9]
It would be nice to add worked examples in the repository, illustrating the full pipeline: define initial particles, run CBO, plot the results. I'd like to work on implementing CBS, but am a little bit stuck getting an example for CBO to run fully. I really like the `DefaultKeywordArguments` technique, but it does make debugging more difficult.

**Comment by rafaelbailo** [comment]
This is now covered in the [Low-level interface examples](https://pdips.github.io/CBX.jl/dev/low_level_examples/#Low-level-interface-examples) of the docs. Closing.
